name: Build Embulk Docker Image

on:
  schedule:
    - cron: '15 0 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      IMAGE_NAME: embulk

    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      
      - name: Fetch Embulk Binary
        run: |
          GITHUB_OWNER=${{ github.repository_owner }} /bin/bash -x fetch.bash

      - name: Set Embulk Metadata
        run: |
          echo "::set-output name=EMBULK_VERSION::$(cat /tmp/artifacts/embulk.version)"
          echo "::set-output name=EMBULK_MD5::$(cat /tmp/artifacts/embulk.md5)"
          echo "::set-output name=EMBULK_TAG::$(cat /tmp/tags | grep $(cat /tmp/artifacts/embulk.version))"
        id: embulk-metadata

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v2
        if: steps.embulk-metadata.outputs.EMBULK_TAG == ''
        with:
          context: .
          push: true
          tags: |
            ${{ github.repository_owner }}/${{ env.IMAGE_NAME }}:latest
            ${{ github.repository_owner }}/${{ env.IMAGE_NAME }}:${{ steps.embulk-metadata.outputs.EMBULK_VERSION }}
            ${{ github.repository_owner }}/${{ env.IMAGE_NAME }}:${{ steps.embulk-metadata.outputs.EMBULK_MD5 }}

      - name: Publish release
        uses: actions/create-release@v1.0.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.embulk-metadata.outputs.EMBULK_VERSION }}
          release_name: v${{ steps.embulk-metadata.outputs.EMBULK_VERSION }}
          draft: false
          prerelease: false

      - name: Save Embulk Metadata
        uses: actions/upload-artifact@v2
        with:
          name: embulk-metadata
          path: /tmp/artifacts/
